### ISSUE TITLE
Project feature/TODO list

### ISSUE THREAD

**Issue by Zekareisoujin** [Zekareisoujin/black-cat#1]
This list serves as both a feature list as well as a TODO plan for what I would like to implement in this application. It is mostly about, but not limited to FE tech stacks and feature. The ordering of the list carry no significance meaning.

As I have more time to spend on this side project I will update this issue to reflect the state of the application.

- [ ] Typescript
- [ ] CSS Module
- [ ] Commitlint
- [ ] ESLint + prettier integration
- [ ] SEO
- [ ] PWA
- [ ] Service Worker
- [ ] Code splitting
- [ ] Monorepo (using Yarn workspace probably)
- [ ] Github CI
- [ ] Development/Production profile
- [ ] Lazy load image
- [ ] SSR
- [ ] Scroll position util
- [ ] Form validation util
- [ ] Skeleton
